### ISSUE TITLE
Update for C11

### ISSUE THREAD

**Issue by greenbagels** [woodruffw/busybeaver#1]
~~update pls thx~~# help

**Comment by woodruffw** [comment]
DIY

**Comment by taimmone** [comment]
I got SCAMMED!!1! dont fall for this!!1

I was browsing Github and I found an ad staying FREE COMMITS!!!! I Put in my information like my user and password and my mommy's credit card information and the next day my code turned into JAVASCRIPT!! I HAD NO COMMITS!!! Then my password was incorrect!!! But I put it in correct and my mommy grounded me for A WEEK because her credit card had "now funds" or whatever I don't even know what that means!!!1! Please give me my commits and my account back!!!1!1!

**Comment by kkartaltepe** [comment]
OwO whats this?
